name: Build and push container images to Quay.io registry
on:
  push:
    branches:
      - master
  schedule:
      - cron: '0 1 * * 3'

jobs:
  build-and-push:
    if: github.repository_owner == 'sclorg'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: "3.9/Dockerfile.c9s"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            tag: "c9s"
            image_name: "python-39-c9s"

          - dockerfile: "3.9-minimal/Dockerfile.rhel8"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            tag: "el8"
            image_name: "python-39-minimal-el8"

          - dockerfile: "3.9-minimal/Dockerfile.c9s"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            tag: "c9s"
            image_name: "python-39-minimal-c9s"

          - dockerfile: "3.11-minimal/Dockerfile.rhel8"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            tag: "el8"
            image_name: "python-311-minimal-el8"

          - dockerfile: "3.11-minimal/Dockerfile.fedora"
            registry_namespace: "fedora"
            quayio_username: "QUAY_IMAGE_FEDORA_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_FEDORA_BUILDER_TOKEN"
            tag: "311"
            image_name: "python-311-minimal"

          - dockerfile: "3.11-minimal/Dockerfile.c9s"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            tag: "c9s"
            image_name: "python-311-minimal-c9s"

          - dockerfile: "3.11/Dockerfile.fedora"
            registry_namespace: "fedora"
            quayio_username: "QUAY_IMAGE_FEDORA_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_FEDORA_BUILDER_TOKEN"
            tag: "311"
            image_name: "python-311"

          - dockerfile: "3.11/Dockerfile.c9s"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            tag: "c9s"
            image_name: "python-311-c9s"

          - dockerfile: "3.12/Dockerfile.fedora"
            registry_namespace: "fedora"
            quayio_username: "QUAY_IMAGE_FEDORA_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_FEDORA_BUILDER_TOKEN"
            tag: "312"
            image_name: "python-312"

          - dockerfile: "3.12/Dockerfile.c9s"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            tag: "c9s"
            image_name: "python-312-c9s"

    steps:
      - name: Build and push to quay.io registry
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: ${{ matrix.registry_namespace }}
          registry_username: ${{ secrets[matrix.quayio_username] }}
          registry_token: ${{ secrets[matrix.quayio_token] }}
          dockerfile: ${{ matrix.dockerfile }}
          tag: ${{ matrix.tag }}
          image_name: ${{ matrix.image_name }}
          archs: amd64, arm64
